config/routes.rb
Property::Application.routes.draw do
  resources :document_types

  resources :documents

  resources :blocks

end

app/models/block.rb
class Block < ActiveRecord::Base
  has_many :documents
  attr_accessible :name, :postcode, :build_date
  validates :name, :presence=>true
  validates :postcode, :presence=>true
  validates :build_date, :presence=>true

  def document_types
    types = Hash.new
    documents.each do |d|
      types[d.document_type.id]=d.document_type
    end
    types
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :document_type
  belongs_to :block
  has_attached_file :doc
  attr_accessible :document_type_id, :block_id, :expiry_date, :doc_file_name, :doc_content_type, :doc_file_size, :doc_updated_at, :doc

  validates :block_id, :presence=>true
  validates :document_type_id, :presence=>true
  validates :doc_file_name, :presence=>true

#TODO - custom validation

end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
  has_many :documents
  attr_accessible :name, :extension, :allow_expiry, :valid_from

  validates :name, :presence=>true, :uniqueness => true
  validates :extension, :presence=>true
  validates :valid_from, :presence=>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @blocks = Block.all
    @doc_types = DocumentType.all
  end

  def show
    @block = Block.find(params[:id])
  end

  def new
    @block = Block.new
  end

  def create
    @block = Block.new(params[:block])
    if @block.save
      redirect_to @block, :notice => "Successfully created block."
    else
      render :action => 'new'
    end
  end

  def edit
    @block = Block.find(params[:id])
  end

  def update
    @block = Block.find(params[:id])
    if @block.update_attributes(params[:block])
      redirect_to @block, :notice  => "Successfully updated block."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @block = Block.find(params[:id])
    @block.destroy
    redirect_to blocks_url, :notice => "Successfully destroyed block."
  end
end

app/controllers/document_types_controller.rb
class DocumentTypesController < ApplicationController

  def new
    @document_type = DocumentType.new
  end

  def create
    @document_type = DocumentType.new(params[:document_type])
    time = params[:document_type][:valid_from]
    p time
    if @document_type.save
      redirect_to blocks_url, :notice => "Successfully created document type."
    else
      render :action => 'new'
    end
  end

  def destroy
    @document_type = DocumentType.find(params[:id])
    @document_type.destroy
    redirect_to blocks_url, :notice => "Successfully destroyed document type."
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def new
    @block = Block.find(params[:id])
    @type = DocumentType.find(params[:doc_type_id])
    unless @block.build_date>@type.valid_from
      redirect_to blocks_url, :notice => "Cannot have an asbestos report for buildings built before 01/01/2000"
    end
    @document = Document.new
  end

  def create
    @document = Document.new(params[:document])
    @type = DocumentType.find(params[:document][:document_type_id])
    @block = Block.find(params[:document][:block_id])
    @document.expiry_date=nil unless @type.allow_expiry
    if @document.save
      redirect_to blocks_url, :notice => "Successfully created document."
    else
      render :action => "new"
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to blocks_url, :notice => "Successfully destroyed document."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
  def fire(document)
    if document.document_type.allow_expiry and document.expiry_date<DateTime.now
      true
    else
      false
    end
  end
end

app/helpers/document_types_helper.rb
module DocumentTypesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/blocks/_form.html.haml
= form_for @block do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :postcode
    %br
    = f.text_field :postcode
  %p
    = f.label :build_date
    %br
    = f.datetime_select :build_date
  %p
    = f.submit

app/views/blocks/edit.html.haml
- title "Edit Block"

= render 'form'

%p
  = link_to "Show", @block
  |
  = link_to "View All", blocks_path

app/views/blocks/index.html.haml
-# This whole things needs alot more helpers and such to tidy it up, yeugh.
- title "Blocks"
%h1= "Property Property Database"
%table
  %tr
    %th Name
    %th Postcode
    %th Build date
    - @doc_types.each do |type|
      %th
        %span.left= type.name+":"
        %span.right= link_to 'Delete type', type, :confirm => 'Are you sure?', :method => :delete
  - for block in @blocks
    %tr
      %td= block.name
      %td= block.postcode
      %td= block.build_date
      - @doc_types.each do |type|
        - if !block.document_types[type.id].blank?
          %td
            %br
            %div.centred= link_to "Download", Document.find_by_block_id_and_document_type_id(block.id, type.id).doc.url(:original, false)
            %div.centred= link_to 'Delete document', Document.find_by_block_id_and_document_type_id(block.id, type.id), :confirm => 'Are you sure?', :method => :delete
            %p= "Uploaded at: "+ Document.find_by_block_id_and_document_type_id(block.id, type.id).updated_at.to_s
            -if fire(Document.find_by_block_id_and_document_type_id(block.id, type.id))
              %p.fire= type.allow_expiry ? "Expiry Date: "+ Document.find_by_block_id_and_document_type_id(block.id, type.id).expiry_date.to_s : ""
            -else
              %p= type.allow_expiry ? "Expiry Date: "+ Document.find_by_block_id_and_document_type_id(block.id, type.id).expiry_date.to_s : ""
        - else
          -unless block.build_date<type.valid_from
            %td= link_to('Add Document', :controller => "documents", :action => "new", :doc_type_id => type.id, :id =>block.id)
          -else
            %td= "Cannot have a and asbestos report for blocks before 01/01/2000"
      %td= link_to 'Show', block
      %td= link_to 'Edit', edit_block_path(block)
      %td= link_to 'Destroy', block, :confirm => 'Are you sure?', :method => :delete

%span=link_to "New Block", new_block_path
%span=link_to "New Document Type", new_document_type_path

app/views/blocks/new.html.haml
- title "New Block"

= render 'form'

%p= link_to "Back to List", blocks_path

app/views/blocks/show.html.haml
- title "Block"

%p
  %strong Name:
  = @block.name
%p
  %strong Postcode:
  = @block.postcode
%p
  %strong Build Date:
  = @block.build_date

%p
  = link_to "Edit", edit_block_path(@block)
  |
  = link_to "Destroy", @block, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", blocks_path

app/views/document_types/_form.html.haml
= form_for @document_type do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :extension
    %br
    = f.text_field :extension
  %p
    = f.label :allow_expiry
    %br
    = f.check_box :allow_expiry
  %p
    = f.label :valid_from
    %br
    = f.datetime_select :valid_from
  %p
    = f.submit

app/views/document_types/new.html.haml
- title "New Document Type"

= render 'form'

%p= link_to "Back to List", document_types_path

app/views/documents/_form.html.haml
= form_for :document, @document, :url => {:action=>'create'}, :html => { :multipart => true } do |f|
  = f.error_messages
  %p
    = f.label "Select File"
    %br
    = f.file_field :doc
  -if @type.allow_expiry
    %p
    = f.label :expiry_date
    %br
    = f.datetime_select :expiry_date
  %input{ :type => "hidden", :value => @block.id, :name => 'document[block_id]'}
  %input{ :type => "hidden", :value => @type.id, :name => 'document[document_type_id]'}
  %p
    = f.submit

app/views/documents/new.html.haml
- title "New Document"

= render 'form'

%p= link_to "Back to List", documents_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Property</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield